apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:blairdrummond/kubeflow-profiles.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <your key goes here>
    -----END OPENSSH PRIVATE KEY-----
