apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubeflow-profiles
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Kubeflow Profile Management

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/blairdrummond/kubeflow-profiles
  - https://github.com/statcan/kubeflow-profiles
  - git@github.com:blairdrummond/kubeflow-profiles.git
  - git@github.com:statcan/kubeflow-profiles.git

  # Only permit applications to deploy to the argocd namespace in the same cluster
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created
  clusterResourceWhitelist:
  - group: 'kubeflow.org'
    kind: Profile

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
